### ISSUE TITLE
Execution issue with ejbca-ejb-cli.jar

### ISSUE THREAD

**Issue by mdhont** [Keyfactor/ejbca-ce#134]
Hi, 

Bitnami developer here. We are working on the release of EJBCA version 7.10.0 but executing the ejbca-ejb-cli.jar is failing with the following error:

```
root@cd60b543682e:/# /opt/bitnami/java/bin/java -jar /opt/bitnami/ejbca/dist//bca-ejb-cli/ejbca-ejb-cli.jar
09:23:52.270 [main] ERROR org.cesecore.jndi.JndiHelper - JNDI name lookup error
javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or in an application resource file: java.naming.factory.initial
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:702) ~[?:?]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305) ~[?:?]
	at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:342) ~[?:?]
	at javax.naming.InitialContext.lookup(InitialContext.java:409) ~[?:?]
	at org.cesecore.jndi.JndiHelper.getRemoteSession(JndiHelper.java:70) [cesecore-common.jar:EJBCA 7.10.0.1 Community (a3751951068a789517bb8b2a7f738cdf00cb0df3)]
	at org.cesecore.util.EjbRemoteHelper.getRemoteSession(EjbRemoteHelper.java:79) [cesecore-common.jar:EJBCA 7.10.0.1 Community (a3751951068a789517bb8b2a7f738cdf00cb0df3)]
	at org.cesecore.util.EjbRemoteHelper.getRemoteSession(EjbRemoteHelper.java:54) [cesecore-common.jar:EJBCA 7.10.0.1 Community (a3751951068a789517bb8b2a7f738cdf00cb0df3)]
	at org.ejbca.ui.cli.ra.AddEndEntityCommand.<init>(AddEndEntityCommand.java:97) [ejbca-ejb-cli.jar:EJBCA 7.10.0.1 Community (a3751951068a789517bb8b2a7f738cdf00cb0df3)]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) [?:?]
	at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780) [?:?]
	at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722) [?:?]
	at java.util.ServiceLoader$3.next(ServiceLoader.java:1395) [?:?]
	at org.ejbca.ui.cli.infrastructure.library.CommandLibrary.<init>(CommandLibrary.java:52) [keyfactor-commons-cli-1.0.0.jar:?]
	at org.ejbca.ui.cli.infrastructure.library.CommandLibrary.<clinit>(CommandLibrary.java:36) [keyfactor-commons-cli-1.0.0.jar:?]
	at org.ejbca.ui.cli.EjbcaEjbCli.main(EjbcaEjbCli.java:38) [ejbca-ejb-cli.jar:EJBCA 7.10.0.1 Community (a3751951068a789517bb8b2a7f738cdf00cb0df3)]
Exception in thread "main" java.util.ServiceConfigurationError: org.ejbca.ui.cli.infrastructure.command.CliCommandPlugin: Provider org.ejbca.ui.cli.ra.AddEndEntityCommand could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
	at org.ejbca.ui.cli.infrastructure.library.CommandLibrary.<init>(CommandLibrary.java:52)
	at org.ejbca.ui.cli.infrastructure.library.CommandLibrary.<clinit>(CommandLibrary.java:36)
	at org.ejbca.ui.cli.EjbcaEjbCli.main(EjbcaEjbCli.java:38)
Caused by: java.lang.NullPointerException
	at org.ejbca.ui.cli.ra.AddEndEntityCommand.<init>(AddEndEntityCommand.java:98)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
	... 5 more
roooot@cd60b543682e:/# /opt/bitnami/java/bin/java -jar /opt/bitnami/ejbca/distjbcejb-cli/ejbca-ejb-cli.jar
09:24:05.062 [main] ERROR org.cesecore.jndi.JndiHelper - JNDI name lookup error
javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or in an application resource file: java.naming.factory.initial
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:702) ~[?:?]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305) ~[?:?]
	at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:342) ~[?:?]
	at javax.naming.InitialContext.lookup(InitialContext.java:409) ~[?:?]
	at org.cesecore.jndi.JndiHelper.getRemoteSession(JndiHelper.java:70) [cesecore-common.jar:EJBCA 7.10.0.1 Community (a3751951068a789517bb8b2a7f738cdf00cb0df3)]
	at org.cesecore.util.EjbRemoteHelper.getRemoteSession(EjbRemoteHelper.java:79) [cesecore-common.jar:EJBCA 7.10.0.1 Community (a3751951068a789517bb8b2a7f738cdf00cb0df3)]
	at org.cesecore.util.EjbRemoteHelper.getRemoteSession(EjbRemoteHelper.java:54) [cesecore-common.jar:EJBCA 7.10.0.1 Community (a3751951068a789517bb8b2a7f738cdf00cb0df3)]
	at org.ejbca.ui.cli.ra.AddEndEntityCommand.<init>(AddEndEntityCommand.java:97) [ejbca-ejb-cli.jar:EJBCA 7.10.0.1 Community (a3751951068a789517bb8b2a7f738cdf00cb0df3)]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) [?:?]
	at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780) [?:?]
	at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722) [?:?]
	at java.util.ServiceLoader$3.next(ServiceLoader.java:1395) [?:?]
	at org.ejbca.ui.cli.infrastructure.library.CommandLibrary.<init>(CommandLibrary.java:52) [keyfactor-commons-cli-1.0.0.jar:?]
	at org.ejbca.ui.cli.infrastructure.library.CommandLibrary.<clinit>(CommandLibrary.java:36) [keyfactor-commons-cli-1.0.0.jar:?]
	at org.ejbca.ui.cli.EjbcaEjbCli.main(EjbcaEjbCli.java:38) [ejbca-ejb-cli.jar:EJBCA 7.10.0.1 Community (a3751951068a789517bb8b2a7f738cdf00cb0df3)]
Exception in thread "main" java.util.ServiceConfigurationError: org.ejbca.ui.cli.infrastructure.command.CliCommandPlugin: Provider org.ejbca.ui.cli.ra.AddEndEntityCommand could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
	at org.ejbca.ui.cli.infrastructure.library.CommandLibrary.<init>(CommandLibrary.java:52)
	at org.ejbca.ui.cli.infrastructure.library.CommandLibrary.<clinit>(CommandLibrary.java:36)
	at org.ejbca.ui.cli.EjbcaEjbCli.main(EjbcaEjbCli.java:38)
Caused by: java.lang.NullPointerException
	at org.ejbca.ui.cli.ra.AddEndEntityCommand.<init>(AddEndEntityCommand.java:98)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
	... 5 more
```

We are using Java version 11.0.15-1 and Wildfly 26.1.1-157 without any changes to the previous configuration. The ejbca-ejb-cli folder contains these files:

```
root@cd60b543682e:/# ls -la /opt/bitnami/ejbca/dist/ejbca-ejb-cli/
total 536
drwxrwxr-x 1 root root   4096 Oct 18 13:51 .
drwxrwxr-x 1 root root   4096 Oct 18 13:51 ..
-rw-rw-r-- 1 root root 501236 Oct 18 13:32 ejbca-ejb-cli.jar
drwxrwxr-x 1 root root   4096 Oct 18 13:51 intresources
-rw-rw-r-- 1 root root    273 Oct 18 13:32 jboss-ejb-client.properties
-rw-rw-r-- 1 root root    146 Oct 18 13:32 jndi.properties
drwxrwxr-x 1 root root   4096 Oct 18 13:51 lib
-rw-rw-r-- 1 root root   2260 Oct 18 13:32 log4j.xml
```

The jndi.properties file content:

```
root@cd60b543682e:/opt/bitnami/ejbca/dist/ejbca-ejb-cli# cat  jndi.properties
# JBoss 7
java.naming.factory.url.pkgs=org.jboss.ejb.client.naming
```

And the jboss-ejb-client.properties file content:

```
root@cd60b543682e:/opt/bitnami/ejbca/dist/ejbca-ejb-cli# cat jboss-ejb-client.properties

remote.connectionprovider.create.options.org.xnio.Options.SSL_ENABLED=false
remote.connections=default
remote.connection.default.host=localhost
remote.connection.default.port = 4447
remote.connection.default.connect.options.org.xnio.Options.SASL_POLICY_NOANONYMOUS=false
```

I couldn't find any changes in the Changelog that could explain why it would fail as we are using the recommended versions of the components.

https://doc.primekey.com/ejbca/ejbca-installation/managing-ejbca-configurations

Could you please help me with this issue?

**Comment by primetomas** [comment]
Do you mean EJBCA 7.10.0.2, which is the latest version?

You didn't upgrade WildFly?

**Comment by mdhont** [comment]
Sorry, yes, the latest EJBCA version and Wildfly version 26.1.2-1.

**Comment by primetomas** [comment]
And you did not update WildFly? 

The error indicates that the "remoting" is not configured so it's working. ejbca-ejb-cli uses the EJB remoting of WildFly. Hence possibly the "JNDI name lookup error". You may find some information form the WildFly server log during startup and configuration of this.

**Comment by mdhont** [comment]
> And you did not update WildFly?

I'm using the latest version (26.1.2-1)

When I configure the remoting it seems to be successful:

```
$ /opt/bitnami/wildfly/bin/jboss-cli.sh --connect '/subsystem=remoting/http-connector=http-remoting-connector:write-attribute(name=connector-ref,value=remoting)'
{
    "outcome" => "success",
    "response-headers" => {
        "operation-requires-reload" => true,

$ /opt/bitnami/wildfly/bin/jboss-cli.sh --connect '/socket-binding-group=standard-sockets/socket-binding=remoting:add(port=4447,interface=management)'
{
    "outcome" => "success",itnami/wildfly/bin/jboss-cli.sh --connect '/socket-binding-group=standard-sockets/socket-binding=remoting:add(port=4447,interface=man
    "response-headers" => {"process-state" => "reload-required"}
}
$ /opt/bitnami/wildfly/bin/jboss-cli.sh --connect '/subsystem=remoting/http-connector=http-remoting-connector:write-attribute(name=connector-ref,value=remoting)'
{
    "outcome" => "success",
    "response-headers" => {
        "operation-requires-reload" => true,
        "process-state" => "reload-required"
    }
}

$ /opt/bitnami/wildfly/bin/jboss-cli.sh --connect '/subsystem=undertow/server=default-server/http-listener=remoting:add(socket-binding=remoting,enable-http2=true)'
{
    "outcome" => "success",
    "response-headers" => {"process-state" => "reload-required"}

$ /opt/bitnami/wildfly/bin/jboss-cli.sh --connect ':reload'
    "outcome" => "success",
    "result" => undefined
}
```

Checking the port 4447 it seems to be running:

```
root@0d328cd8456d:/# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9990          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.11:36825        0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:8443          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:4447          0.0.0.0:*               LISTEN      -
udp        0      0 127.0.0.11:53200        0.0.0.0:*                           -
```

**Comment by primetomas** [comment]
I just made a manual install myself, using the latest version of WildFly 26, following the documentation here:
https://doc.primekey.com/ejbca/ejbca-installation/application-servers/wildfly-26

And the cli works for me.
Do you have a jndi.properties and jboss-ejb-client.properties with the correct values.

**Comment by mdhont** [comment]
Ok, thanks but I have found the solution. The reason why it failed was that we didn't have the `bin/client/jboss-client.jar` in the Wildfly directory in the compilation step, which is necessary for the newer Wildfly versions.
