### ISSUE TITLE
Mariadb and datastore not working

### ISSUE THREAD

**Issue by oculos** [Keyfactor/ejbca-ce#159]
Hi,

I tried to install Ejbca on Wildfly 26, following the instructions found here: https://doc.primekey.com/ejbca/ejbca-installation/application-servers/wildfly-26

However, I have these recurrent problems:

1 - I follow all the instructions, sometimes skipping the optional instructions. Tried with 2 and 3 port separation. After importing the `superadmin.p12` to Firefox, I still get `SSL_ERROR_HANDSHAKE_FAILURE_ALERT`. I could access the public site (http, not https) at port 8080.
Weirdly enough, I don't get even to trust the p12 on a Mac.

2 - If I restart the wildfly service, then the logs tell me that the httpsTS keystore fails to start, and that the MariaDB driver isn't installed: 

```
2022-11-14 20:31:56,050 INFO  [org.cesecore.audit.impl.log4j.Log4jDevice] (default task-2) 2022-11-14 20:31:56+01:00;RA_EDITENDENTITY;SUCCESS;RA;CORE;ejbca;-946314377;;superadmin;msg=Password changed for end entity superadmin.
2022-11-14 20:31:58,789 INFO  [org.cesecore.audit.impl.log4j.Log4jDevice] (default task-2) 2022-11-14 20:31:58+01:00;ACCESS_CONTROL;SUCCESS;ACCESSCONTROL;CORE;ejbca;;;;resource0=/ca/-946314377
2022-11-14 20:36:06,830 INFO  [org.ejbca.core.ejb.services.ServiceSessionBean] (EJB default - 1) Timer was triggered. Trying to run service with ID 0.
2022-11-14 20:36:07,156 INFO  [org.cesecore.certificates.certificate.CertificateStoreSessionBean] (EJB default - 2) Reloading CA certificate cache.
2022-11-14 20:36:07,159 INFO  [org.cesecore.certificates.certificate.CertificateStoreSessionBean] (EJB default - 2) Reloaded CA certificate cache with 1 certificates
2022-11-14 20:41:07,161 INFO  [org.cesecore.certificates.certificate.CertificateStoreSessionBean] (EJB default - 1) Reloading CA certificate cache.
2022-11-14 20:41:07,170 INFO  [org.cesecore.certificates.certificate.CertificateStoreSessionBean] (EJB default - 1) Reloaded CA certificate cache with 1 certificates
2022-11-14 20:42:40,509 INFO  [org.ejbca.core.ejb.StartupSingletonBean] (ServerService Thread Pool -- 113) Destroy, EJBCA shutdown.
2022-11-14 20:42:40,642 INFO  [org.infinispan.manager.DefaultCacheManager] (ServerService Thread Pool -- 137) Stopping cache manager null on null
2022-11-14 20:42:40,653 INFO  [org.infinispan.manager.DefaultCacheManager] (ServerService Thread Pool -- 138) Stopping cache manager null on null
2022-11-14 20:42:45,356 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service org.wildfly.security.key-store.httpsTS: org.jboss.msc.service.StartException in service org.wildfly.security.key-store.httpsTS: WFLYELY00004: Unable to start the service.
	at org.wildfly.extension.elytron@18.0.0.Final//org.wildfly.extension.elytron.KeyStoreService.start(KeyStoreService.java:200)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1363)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.FileNotFoundException: /opt/wildfly/standalone/configuration/keystore/truststore.jks (Permission denied)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.wildfly.extension.elytron@18.0.0.Final//org.wildfly.extension.elytron.KeyStoreService.start(KeyStoreService.java:153)
	... 8 more

2022-11-14 20:42:45,407 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service org.wildfly.security.key-store.httpsKS: org.jboss.msc.service.StartException in service org.wildfly.security.key-store.httpsKS: WFLYELY00004: Unable to start the service.
	at org.wildfly.extension.elytron@18.0.0.Final//org.wildfly.extension.elytron.KeyStoreService.start(KeyStoreService.java:200)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1363)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.FileNotFoundException: /opt/wildfly/standalone/configuration/keystore/keystore.jks (Permission denied)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.wildfly.extension.elytron@18.0.0.Final//org.wildfly.extension.elytron.KeyStoreService.start(KeyStoreService.java:153)
	... 8 more

2022-11-14 20:42:49,066 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "datasources"),
    ("data-source" => "ejbcads")
]) - failure description: {
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.jdbc-driver.mariadb-java-client_jar"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => [
        "jboss.driver-demander.java:/EjbcaDS is missing [jboss.jdbc-driver.mariadb-java-client_jar]",
        "org.wildfly.data-source.ejbcads is missing [jboss.jdbc-driver.mariadb-java-client_jar]"
    ]
}
2022-11-14 20:42:49,070 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "elytron"),
    ("key-store" => "httpsKS")
]) - failure description: {"WFLYCTL0080: Failed services" => {"org.wildfly.security.key-store.httpsKS" => "WFLYELY00004: Unable to start the service.
    Caused by: java.io.FileNotFoundException: /opt/wildfly/standalone/configuration/keystore/keystore.jks (Permission denied)"}}
2022-11-14 20:42:49,070 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "elytron"),
    ("key-store" => "httpsTS")
]) - failure description: {"WFLYCTL0080: Failed services" => {"org.wildfly.security.key-store.httpsTS" => "WFLYELY00004: Unable to start the service.
    Caused by: java.io.FileNotFoundException: /opt/wildfly/standalone/configuration/keystore/truststore.jks (Permission denied)"}}
2022-11-14 20:42:49,073 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "datasources"),
    ("data-source" => "ejbcads")
]) - failure description: {
    "WFLYCTL0412: Required services that are not installed:" => [
        "jboss.jdbc-driver.mariadb-java-client_jar",
        "jboss.jdbc-driver.mariadb-java-client_jar"
    ],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => [
        "jboss.driver-demander.java:/EjbcaDS is missing [jboss.jdbc-driver.mariadb-java-client_jar]",
        "org.wildfly.data-source.ejbcads is missing [jboss.jdbc-driver.mariadb-java-client_jar]",
        "org.wildfly.data-source.ejbcads is missing [jboss.jdbc-driver.mariadb-java-client_jar]"
    ]
}
2022-11-14 20:42:49,180 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 26.0.0.Final (WildFly Core 18.0.0.Final) started (with errors) in 7698ms - Started 341 of 614 services (30 services failed or missing dependencies, 341 services are lazy, passive or on-demand)
```

I've tried installing from scratch a few times, but end up with these two problems every time. 

Any hints on how to get this done? 

Best,

Francis

**Comment by oculos** [comment]
Moving this to the Q&A section of the discussion.

**Comment by sbarnes-tecnica** [comment]
I ran into this same issue when following the documentation. The cause was I was running
`ant deploy-keystore` as root/sudo, and so the deployed keystore files were not owned by the wildfly user.
