### ISSUE TITLE
Installation error in version 7.11.0

### ISSUE THREAD

**Issue by darkpastiurs** [Keyfactor/ejbca-ce#225]
I wanted to report an error when executing the command:

`ant runinstall`

It returns the following error:

```
ejbca:initCA:
     [echo] Initializing CA with 'ManagementCA' 'CN=ManagementCA,O=Test Local,C=SV' 'soft' '<ca.tokenpassword hidden>' 'secp384r1' 'ECDSA' '3650' '2.5.29.32.0' 'SHA512WithECDSA'   -superadmincn 'SuperAdmin'...
     [java] Exception in thread "main" java.util.ServiceConfigurationError: org.ejbca.ui.cli.infrastructure.command.CliCommandPlugin: Provider org.ejbca.ui.cli.keybind.InternalKeyBindingCreateCommand could not be instantiated
     [java]     at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
     [java]     at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
     [java]     at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
     [java]     at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
     [java]     at org.ejbca.ui.cli.infrastructure.library.CommandLibrary.<init>(CommandLibrary.java:58)
     [java]     at org.ejbca.ui.cli.infrastructure.library.CommandLibrary.<clinit>(CommandLibrary.java:39)
     [java]     at org.ejbca.ui.cli.EjbcaEjbCli.main(EjbcaEjbCli.java:32)
     [java] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.lang.reflect.Method jdk.proxy2.$Proxy5.m0 accessible: module jdk.proxy2 does not "opens jdk.proxy2" to unnamed module @619713e5
     [java]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
     [java]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
     [java]     at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
     [java]     at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
     [java]     at org.jboss.ejb.client.EJBProxyInformation$1.doCompute(EJBProxyInformation.java:101)
     [java]     at org.jboss.ejb.client.EJBProxyInformation$1.computeValue(EJBProxyInformation.java:72)
     [java]     at org.jboss.ejb.client.EJBProxyInformation$1.computeValue(EJBProxyInformation.java:66)
     [java]     at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
     [java]     at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
     [java]     at java.base/java.lang.ClassValue.get(ClassValue.java:116)
     [java]     at org.jboss.ejb.client.EJBProxyInformation.forViewType(EJBProxyInformation.java:242)
     [java]     at org.jboss.ejb.client.EJBLocator.getProxyInformation(EJBLocator.java:375)
     [java]     at org.jboss.ejb.client.EJBLocator.getProxyConstructor(EJBLocator.java:370)
     [java]     at org.jboss.ejb.client.EJBLocator.createProxyInstance(EJBLocator.java:387)
     [java]     at org.jboss.ejb.client.EJBClient.createProxy(EJBClient.java:161)
     [java]     at org.jboss.ejb.client.EJBRootContext.lookupNative(EJBRootContext.java:166)
     [java]     at org.wildfly.naming.client.AbstractContext.lookup(AbstractContext.java:84)
     [java]     at org.wildfly.naming.client.WildFlyRootContext.lookup(WildFlyRootContext.java:144)
     [java]     at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
     [java]     at org.cesecore.jndi.JndiHelper.getRemoteSession(JndiHelper.java:75)
     [java]     at org.cesecore.util.EjbRemoteHelper.getRemoteSession(EjbRemoteHelper.java:79)
     [java]     at org.cesecore.util.EjbRemoteHelper.getRemoteSession(EjbRemoteHelper.java:54)
     [java]     at org.ejbca.ui.cli.keybind.InternalKeyBindingCreateCommand.<init>(InternalKeyBindingCreateCommand.java:70)
     [java]     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     [java]     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
     [java]     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     [java]     at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
     [java]     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
     [java]     at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
     [java]     ... 5 more

BUILD FAILED
/opt/servers/ejbca/ejbca_ce_7_11_0/build.xml:72: The following error occurred while executing this line:
/opt/servers/ejbca/ejbca_ce_7_11_0/bin/cli.xml:98: The following error occurred while executing this line:
/opt/servers/ejbca/ejbca_ce_7_11_0/bin/cli.xml:126: The following error occurred while executing this line:
/opt/servers/ejbca/ejbca_ce_7_11_0/bin/cli.xml:532: Java returned: 1
```

The server logs (`server.log, cesecore-audit.log`) doesn't show anything 

I've tried to install EJBCA in the following environment:

Application server:
`JBoss EAP 7.4`

OS:
```
AME="openSUSE Tumbleweed"
VERSION="20230118"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20230118"
PRETTY_NAME=openSUSE Tumbleweed
```

JDK:
```
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+0-suse-3.1-x8664)
OpenJDK 64-Bit Server VM (build 17.0.5+0-suse-3.1-x8664, mixed mode)
```

Alternatively I have also tried with the JDK:
```
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+0-suse-2.1-x8664)
OpenJDK 64-Bit Server VM (build 11.0.17+0-suse-2.1-x8664, mixed mode)
```

**Comment by primetomas** [comment]
JDK 17 is not yet officially supported. Use JDK 11. If you built previously with JDK 17 you should clean it with "ant clean" after you have switched to Java 11.

**Comment by darkpastiurs** [comment]
Thanks, the problem was the JDK, at the same time, that the OS was ignoring the environment variables that it established which JDK to use and always ended up using 17, I tried a VM with a clean installation with OpenJDK 11 and everything worked fine
