### ISSUE TITLE
Integration EJBCA in docker container with SMTP server.

### ISSUE THREAD

**Issue by plech-sec** [Keyfactor/ejbca-ce#33]
Hi, 
I'm trying to integrate EJBCA Community 7.4.3.2 (docker image) with an SMTP server to send notifications via email from RA.
I set the SMTP_DESTINATION / PORT variables - the configuration in standalone.xml is changed correctly, but the problem appears when sending the notification - a problem with STARTTLS.
`Unable to send email: : com.sun.                                                                                                            mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first`

Command `docker exec container_id printenv` - it only shows SMTP_DESTINATION and PORT, STARTLS parameter is missing.

I'm using this suggestion https://sourceforge.net/p/ejbca/discussion/123122/thread/f2eea5ed74/#a04c/6040 but the problem with
 email still occurs.

when launching the container, it adds  JAVA_OPTS ( accoridng to https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html)
`-e JAVA_OPTS="  -server   -Xms128m -Xmx5626m -Xss256k -XX:MetaspaceSize=160m -XX:MaxMetaspaceSize=256m -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:+ExitOnOutOfMemoryError -Djdk.tls.ephemeralDHKeySize=2048 -Djava.net.preferIPv4Stack=true -Djavax.net.debug=ssl:handshake -Xlog:gc*:verbose_gc.log:time -Djava.security.egd=file:/dev/random -Dcontainer.database.name=mysql -Dcontainer.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect -Dhibernate.dialect.storage_engine=innodb -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED  --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED -Dmail.smtp.starttls.enable=true"`

but when sending the notification, the STARTLS error still appears

`JAVA_OPTS already set in environment; overriding default settings with values:   -server   -Xms128m -Xmx5626m -Xss256k -XX:MetaspaceSize=160m -XX:MaxMetaspaceSize=256m -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:+ExitOnOutOfMemoryError -Djdk.tls.ephemeralDHKeySize=2048 -Djava.net.preferIPv4Stack=true -Djavax.net.debug=ssl:handshake -Xlog:gc*:verbose_gc.log:time -Djava.security.egd=file:/dev/random -Dcontainer.database.name=mysql -Dcontainer.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect -Dhibernate.dialect.storage_engine=innodb -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED  --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED -Dmail.smtp.starttls.enable=true
  JAVA_OPTS:    -server   -Xms128m -Xmx5626m -Xss256k -XX:MetaspaceSize=160m -XX:MaxMetaspaceSize=256m -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:+ExitOnOutOfMemoryError -Djdk.tls.ephemeralDHKeySize=2048 -Djava.net.preferIPv4Stack=true -Djavax.net.debug=ssl:handshake -Xlog:gc*:verbose_gc.log:time -Djava.security.egd=file:/dev/random -Dcontainer.database.name=mysql -Dcontainer.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect -Dhibernate.dialect.storage_engine=innodb -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED  --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED -Dmail.smtp.starttls.enable=true  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED
2022-04-14 01:28:42,738+0000 INFO  [org.cesecore.audit.impl.log4j.Log4jDevice] (default task-1) 2022-04-14 01:28:42+00:00;RA_ADDENDENTITY;SUCCESS;RA;CORE;172.18.3.64 (TRANSPORT_CONFIDENTIAL);-20934253;;superadmin;msg=Added end entity superadmin.;caid=-20934253;cardnumber=;certificateprofileid=1;endentityprofileid=1;status=10;subjectAltName=;subjectDN=B64:Q049U3VwZXJBZG1pbg==;subjectEmail=;tokentype=2;type=1;username=superadmin
2022-04-14 01:41:03,269+0000 ERROR [org.ejbca.util.mail.MailSender] (default task-1) Unable to send email: : com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first
        at javax.mail.api@1.6.5//com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2374)
        at javax.mail.api@1.6.5//com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1808)
        at javax.mail.api@1.6.5//com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1285)
        at javax.mail.api@1.6.5//javax.mail.Transport.send0(Transport.java:231)
        at javax.mail.api@1.6.5//javax.mail.Transport.send(Transport.java:100)
        at deployment.ejbca.ear//org.ejbca.util.mail.MailSender.sendMailWithSession(MailSender.java:174)`

Thanks for every suggestion.

**Comment by plech-sec** [comment]
Resolved by the latest version of the image.
https://hub.docker.com/layers/ejbca-ce/primekey/ejbca-ce/latest/images/sha256-648a4f838a05d5c574b7a98c735db63069f358bbcbed94981ce193ec490dc9f3?context=explore
