### ISSUE TITLE
openjdk 11.0.15 breaks PKCS #11 HSM support

### ISSUE THREAD

**Issue by mperretta1** [Keyfactor/ejbca-ce#37]
Latest docker container primekey/ejbca-ce:7.4.3.2 moved from openjdk 11.0.11 to 11.0.15. This seems to break the sun.security.pkcs11.wrapper. 

After moving back to 11.0.11 everything works again using the same PKCS #11 library.

2022-05-09 17:55:40,525+0000 ERROR
[org.cesecore.keys.token.p11.Pkcs11Wrapper] (default task-1) Method
getInstance was not found in class
sun.security.pkcs11.wrapper.PKCS11.CK_C_INITIALIZE_ARGS, this may be
due to a change in the underlying library.:
java.lang.NoSuchMethodException:
sun.security.pkcs11.wrapper.PKCS11.getInstance(java.lang.String,
java.lang.String, sun.security.pkcs11.wrapper.CK_C_INITIALIZE_ARGS,
boolean)
at java.base/java.lang.Class.getDeclaredMethod(Unknown Source)
at
deployment.ejbca.ear//org.cesecore.keys.token.p11.Pkcs11Wrapper.<init>(
Pkcs11Wrapper.java:103)
at
deployment.ejbca.ear//org.cesecore.keys.token.p11.Pkcs11Wrapper.getInst
ance(Pkcs11Wrapper.java:171)
at
deployment.ejbca.ear//org.cesecore.keys.token.p11.Pkcs11SlotLabel.getPr
ovider(Pkcs11SlotLabel.java:123)
at
deployment.ejbca.ear//org.cesecore.keys.token.p11.Pkcs11SlotLabel.getP1
1Provider(Pkcs11SlotLabel.java:554)
at
deployment.ejbca.ear//org.cesecore.keys.token.p11.Pkcs11SlotLabel.getP1
1Provider(Pkcs11SlotLabel.java:519)
at
deployment.ejbca.ear//org.cesecore.keys.token.p11.P11Slot.<init>(P11Slo
t.java:59)
at
deployment.ejbca.ear//org.cesecore.keys.token.p11.P11Slot.getInstance(P
11Slot.java:248)
at
deployment.ejbca.ear//org.cesecore.keys.token.p11.P11Slot.getInstance(P
11Slot.java:205)
at
deployment.ejbca.ear//org.cesecore.keys.token.p11.P11Slot.getInstance(P
11Slot.java:183)
at
deployment.ejbca.ear//org.cesecore.keys.token.PKCS11CryptoToken.delayed
Init(PKCS11CryptoToken.java:123)
at
deployment.ejbca.ear//org.cesecore.keys.token.PKCS11CryptoToken.getP11s
lotWithDelayedInit(PKCS11CryptoToken.java:289)
at
deployment.ejbca.ear//org.cesecore.keys.token.PKCS11CryptoToken.activat
e(PKCS11CryptoToken.java:146)
at
deployment.ejbca.ear//org.cesecore.keys.token.BaseCryptoToken.autoActiv
ate(BaseCryptoToken.java:114)
at
deployment.ejbca.ear//org.cesecore.keys.token.BaseCryptoToken.getKeySto
re(BaseCryptoToken.java:97)
at
deployment.ejbca.ear//org.cesecore.keys.token.BaseCryptoToken.getTokenS
tatus(BaseCryptoToken.java:640)
at deployment.ejbca.ear.cesecore-
ejb.jar//org.cesecore.keys.token.CryptoTokenManagementSessionBean.getCr
yptoTokenInfo(CryptoTokenManagementSessionBean.java:117)
at deployment.ejbca.ear.cesecore-
ejb.jar//org.cesecore.keys.token.CryptoTokenManagementSessionBean.getCr
yptoTokenInfos(CryptoTokenManagementSessionBean.java:105)
at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown
Source)
at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unkn
own Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.jboss.as.ee@22.0.1.Final//org.jboss.as.ee.component.Mana
gedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodI
nterceptor.java:52)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext$Invocation.proceed(InterceptorContext.java:509)
at org.jboss.as.weld.common@22.0.1.Final//org.jboss.as.weld.int
erceptors.Jsr299BindingsInterceptor.delegateInterception(Jsr299Bindings
Interceptor.java:79)
at org.jboss.as.weld.common@22.0.1.Final//org.jboss.as.weld.int
erceptors.Jsr299BindingsInterceptor.doMethodInterception(Jsr299Bindings
Interceptor.java:89)
at org.jboss.as.weld.common@22.0.1.Final//org.jboss.as.weld.int
erceptors.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInt
erceptor.java:102)
at org.jboss.as.ee@22.0.1.Final//org.jboss.as.ee.component.inte
rceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFact
ory.java:63)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.as.ejb3@22.0.1.Final//org.jboss.as.ejb3.component.
invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionT
imeInterceptor.java:43)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.as.jpa@22.0.1.Final//org.jboss.as.jpa.interceptor.
SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:
47)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.as.ee@22.0.1.Final//org.jboss.as.ee.concurrent.Con
currentContextInterceptor.processInvocation(ConcurrentContextIntercepto
r.java:45)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Initi
alInterceptor.processInvocation(InitialInterceptor.java:40)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Chain
edInterceptor.processInvocation(ChainedInterceptor.java:53)
at org.jboss.as.ee@22.0.1.Final//org.jboss.as.ee.component.inte
rceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDisp
atcherInterceptor.java:52)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.as.ejb3@22.0.1.Final//org.jboss.as.ejb3.component.
pool.PooledInstanceInterceptor.processInvocation(PooledInstanceIntercep
tor.java:51)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.as.ejb3@22.0.1.Final//org.jboss.as.ejb3.component.
interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSet
upInterceptor.java:54)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.as.ejb3@22.0.1.Final//org.jboss.as.ejb3.tx.CMTTxIn
terceptor.invokeInNoTx(CMTTxInterceptor.java:230)
at org.jboss.as.ejb3@22.0.1.Final//org.jboss.as.ejb3.tx.CMTTxIn
terceptor.supports(CMTTxInterceptor.java:444)
at org.jboss.as.ejb3@22.0.1.Final//org.jboss.as.ejb3.tx.CMTTxIn
terceptor.processInvocation(CMTTxInterceptor.java:162)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext$Invocation.proceed(InterceptorContext.java:509)
at org.jboss.weld.core@3.1.5.Final//org.jboss.weld.module.ejb.A
bstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBReq
uestScopeActivationInterceptor.java:72)
at org.jboss.as.weld.common@22.0.1.Final//org.jboss.as.weld.ejb
.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScope
ActivationInterceptor.java:89)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.as.ejb3@22.0.1.Final//org.jboss.as.ejb3.component.
interceptors.CurrentInvocationContextInterceptor.processInvocation(Curr
entInvocationContextInterceptor.java:41)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.as.ejb3@22.0.1.Final//org.jboss.as.ejb3.component.
invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterce
ptor.java:47)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.as.ejb3@22.0.1.Final//org.jboss.as.ejb3.security.I
dentityOutflowInterceptor.processInvocation(IdentityOutflowInterceptor.
java:73)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.as.ejb3@22.0.1.Final//org.jboss.as.ejb3.security.S
ecurityDomainInterceptor.processInvocation(SecurityDomainInterceptor.ja
va:44)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.as.ejb3@22.0.1.Final//org.jboss.as.ejb3.deployment
.processors.StartupAwaitInterceptor.processInvocation(StartupAwaitInter
ceptor.java:22)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.as.ejb3@22.0.1.Final//org.jboss.as.ejb3.component.
interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInt
erceptorFactory.java:64)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.as.ejb3@22.0.1.Final//org.jboss.as.ejb3.component.
interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.ja
va:67)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.as.ee@22.0.1.Final//org.jboss.as.ee.component.Name
spaceContextInterceptor.processInvocation(NamespaceContextInterceptor.j
ava:50)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Conte
xtClassLoaderInterceptor.processInvocation(ContextClassLoaderIntercepto
r.java:60)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.run(InterceptorContext.java:438)
at org.wildfly.security.elytron-private@1.14.1.Final//org.wildf
ly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityMan
ager.java:633)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Acces
sCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:5
7)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Inter
ceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.Chain
edInterceptor.processInvocation(ChainedInterceptor.java:53)
at org.jboss.as.ee@22.0.1.Final//org.jboss.as.ee.component.View
Service$View.invoke(ViewService.java:198)
at org.jboss.as.ee@22.0.1.Final//org.jboss.as.ee.component.View
Description$1.processInvocation(ViewDescription.java:191)
at org.jboss.as.ee@22.0.1.Final//org.jboss.as.ee.component.Prox
yInvocationHandler.invoke(ProxyInvocationHandler.java:81)
at deployment.ejbca.ear.cesecore-
ejb.jar//org.cesecore.keys.token.CryptoTokenManagementSessionLocal$$$vi
ew47.getCryptoTokenInfos(Unknown Source)
at
deployment.ejbca.ear.adminweb.war//org.ejbca.ui.web.admin.cryptotoken.C
ryptoTokenMBean.getCryptoTokenGuiList(CryptoTokenMBean.java:757)
at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown
Source)
at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unkn
own Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at javax.el.api@2.0.0.Final//javax.el.BeanELResolver.getValue(B
eanELResolver.java:186)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.el.DemuxComposit
eELResolver._getValue(DemuxCompositeELResolver.java:156)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.el.DemuxComposit
eELResolver.getValue(DemuxCompositeELResolver.java:184)
at org.glassfish.jakarta.el@3.0.3.jbossorg-2//com.sun.el.parser
.AstValue.getValue(AstValue.java:114)
at org.glassfish.jakarta.el@3.0.3.jbossorg-2//com.sun.el.parser
.AstValue.getValue(AstValue.java:177)
at org.glassfish.jakarta.el@3.0.3.jbossorg-2//com.sun.el.ValueE
xpressionImpl.getValue(ValueExpressionImpl.java:183)
at org.jboss.weld.core@3.1.5.Final//org.jboss.weld.module.web.e
l.WeldValueExpression.getValue(WeldValueExpression.java:50)
at org.jboss.weld.core@3.1.5.Final//org.jboss.weld.module.web.e
l.WeldValueExpression.getValue(WeldValueExpression.java:50)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.facelets.el.TagV
alueExpression.getValue(TagValueExpression.java:73)
at javax.faces.api@3.0.0.SP04//javax.faces.component.ComponentS
tateHelper.eval(ComponentStateHelper.java:170)
at javax.faces.api@3.0.0.SP04//javax.faces.component.ComponentS
tateHelper.eval(ComponentStateHelper.java:157)
at javax.faces.api@3.0.0.SP04//javax.faces.component.UIData.get
Value(UIData.java:736)
at javax.faces.api@3.0.0.SP04//javax.faces.component.UIData.get
DataModel(UIData.java:1849)
at javax.faces.api@3.0.0.SP04//javax.faces.component.UIData.set
RowIndexWithoutRowStatePreserved(UIData.java:479)
at javax.faces.api@3.0.0.SP04//javax.faces.component.UIData.set
RowIndex(UIData.java:468)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.renderkit.html_b
asic.TableRenderer.encodeBegin(TableRenderer.java:57)
at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponen
tBase.encodeBegin(UIComponentBase.java:540)
at javax.faces.api@3.0.0.SP04//javax.faces.component.UIData.enc
odeBegin(UIData.java:1153)
at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponen
t.encodeAll(UIComponent.java:1644)
at javax.faces.api@3.0.0.SP04//javax.faces.render.Renderer.enco
deChildren(Renderer.java:152)
at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponen
tBase.encodeChildren(UIComponentBase.java:566)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.renderkit.html_b
asic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:278)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.renderkit.html_b
asic.GroupRenderer.encodeChildren(GroupRenderer.java:90)
at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponen
tBase.encodeChildren(UIComponentBase.java:566)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.renderkit.html_b
asic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:278)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.renderkit.html_b
asic.GroupRenderer.encodeChildren(GroupRenderer.java:90)
at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponen
tBase.encodeChildren(UIComponentBase.java:566)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.renderkit.html_b
asic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:278)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.renderkit.html_b
asic.GroupRenderer.encodeChildren(GroupRenderer.java:90)
at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponen
tBase.encodeChildren(UIComponentBase.java:566)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.renderkit.html_b
asic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:278)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.renderkit.html_b
asic.GroupRenderer.encodeChildren(GroupRenderer.java:90)
at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponen
tBase.encodeChildren(UIComponentBase.java:566)
at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponen
t.encodeAll(UIComponent.java:1647)
at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponen
t.encodeAll(UIComponent.java:1650)
at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponen
t.encodeAll(UIComponent.java:1650)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.application.view
.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.jav
a:468)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.application.view
.MultiViewHandler.renderView(MultiViewHandler.java:170)
at javax.faces.api@3.0.0.SP04//javax.faces.application.ViewHand
lerWrapper.renderView(ViewHandlerWrapper.java:132)
at
deployment.ejbca.ear.adminweb.war//org.apache.myfaces.tomahawk.applicat
ion.ResourceViewHandlerWrapper.renderView(ResourceViewHandlerWrapper.ja
va:169)
at javax.faces.api@3.0.0.SP04//javax.faces.application.ViewHand
lerWrapper.renderView(ViewHandlerWrapper.java:132)
at javax.faces.api@3.0.0.SP04//javax.faces.application.ViewHand
lerWrapper.renderView(ViewHandlerWrapper.java:132)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.lifecycle.Render
ResponsePhase.execute(RenderResponsePhase.java:102)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.lifecycle.Phase.
doPhase(Phase.java:76)
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.lifecycle.Lifecy
cleImpl.render(LifecycleImpl.java:199)
at javax.faces.api@3.0.0.SP04//javax.faces.webapp.FacesServlet.
executeLifecyle(FacesServlet.java:708)
at javax.faces.api@3.0.0.SP04//javax.faces.webapp.FacesServlet.
service(FacesServlet.java:451)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.ServletHandler.handleRequest(ServletHandler.java:74)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
at
deployment.ejbca.ear.adminweb.war//org.ejbca.ui.web.admin.NoCacheFilter
.doFilter(NoCacheFilter.java:68)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.core.Ma
nagedFilter.doFilter(ManagedFilter.java:61)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
at
deployment.ejbca.ear//org.owasp.filters.ContentSecurityPolicyFilter.doF
ilter(ContentSecurityPolicyFilter.java:223)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.core.Ma
nagedFilter.doFilter(ManagedFilter.java:61)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
at
deployment.ejbca.ear.adminweb.war//org.ejbca.ui.web.admin.ProxiedAuthen
ticationFilter.doFilter(ProxiedAuthenticationFilter.java:104)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.core.Ma
nagedFilter.doFilter(ManagedFilter.java:61)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.FilterHandler.handleRequest(FilterHandler.java:84)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRole
Handler.java:62)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.ServletChain$1.handleRequest(ServletChain.java:68)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.jav
a:36)
at org.wildfly.extension.undertow@22.0.1.Final//org.wildfly.ext
ension.undertow.security.SecurityContextAssociationHandler.handleReques
t(SecurityContextAssociationHandler.java:78)
at io.undertow.core@2.2.4.Final//io.undertow.server.handlers.Pr
edicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.security.SSLInformationAssociationHandler.handleRequest(SSLInformatio
nAssociationHandler.java:117)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthen
ticationCallHandler.java:57)
at io.undertow.core@2.2.4.Final//io.undertow.server.handlers.Pr
edicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.core@2.2.4.Final//io.undertow.security.handlers.
AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintH
andler.java:53)
at io.undertow.core@2.2.4.Final//io.undertow.security.handlers.
AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHan
dler.java:46)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.security.ServletConfidentialityConstraintHandler.handleRequest(Servle
tConfidentialityConstraintHandler.java:64)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.security.ServletSecurityConstraintHandler.handleRequest(ServletSecuri
tyConstraintHandler.java:59)
at io.undertow.core@2.2.4.Final//io.undertow.security.handlers.
AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsH
andler.java:60)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthen
ticatedSessionHandler.java:77)
at io.undertow.core@2.2.4.Final//io.undertow.security.handlers.
NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.j
ava:50)
at io.undertow.core@2.2.4.Final//io.undertow.security.handlers.
AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurit
yContextAssociationHandler.java:43)
at io.undertow.core@2.2.4.Final//io.undertow.server.handlers.Pr
edicateHandler.handleRequest(PredicateHandler.java:43)
at org.wildfly.extension.undertow@22.0.1.Final//org.wildfly.ext
ension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCCo
ntextIdHandler.java:61)
at io.undertow.core@2.2.4.Final//io.undertow.server.handlers.Pr
edicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
at io.undertow.core@2.2.4.Final//io.undertow.server.handlers.Pr
edicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:2
69)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.core.Se
rvletRequestContextThreadSetupAction$1.call(ServletRequestContextThread
SetupAction.java:48)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.core.Co
ntextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:4
3)
at org.wildfly.extension.undertow@22.0.1.Final//org.wildfly.ext
ension.undertow.security.SecurityContextThreadSetupAction.lambda$create
$0(SecurityContextThreadSetupAction.java:105)
at org.wildfly.extension.undertow@22.0.1.Final//org.wildfly.ext
ension.undertow.deployment.UndertowDeploymentInfoService$UndertowThread
SetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
at org.wildfly.extension.undertow@22.0.1.Final//org.wildfly.ext
ension.undertow.deployment.UndertowDeploymentInfoService$UndertowThread
SetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
at org.wildfly.extension.undertow@22.0.1.Final//org.wildfly.ext
ension.undertow.deployment.UndertowDeploymentInfoService$UndertowThread
SetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
at org.wildfly.extension.undertow@22.0.1.Final//org.wildfly.ext
ension.undertow.deployment.UndertowDeploymentInfoService$UndertowThread
SetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
at org.wildfly.extension.undertow@22.0.1.Final//org.wildfly.ext
ension.undertow.deployment.UndertowDeploymentInfoService$UndertowThread
SetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handler
s.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
at io.undertow.core@2.2.4.Final//io.undertow.server.Connectors.
executeRootHandler(Connectors.java:387)
at io.undertow.core@2.2.4.Final//io.undertow.server.HttpServerE
xchange$1.run(HttpServerExchange.java:841)
at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClas
sLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQue
ueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQue
ueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQue
ueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
at org.jboss.xnio@3.8.4.Final//org.xnio.XnioWorker$WorkerThread
Factory$1$1.run(XnioWorker.java:1280)
at java.base/java.lang.Thread.run(Unknown Source)</init></init>

**Comment by primetomas** [comment]
I tested on Ubuntu now, with OpenJDK 11.0.15, but it works there. If you can enable debug logging there should be interesting things logged. This is a log entry that you can look for to compare. Look for "PKCS11SlotListWrapperFactory of type".

`
2022-05-16 11:34:03,635 DEBUG [org.cesecore.keys.token.PKCS11SlotListWrapperHelper] (default task-1) Using PKCS11SlotListWrapperFactory of type org.cesecore.keys.token.p11.SunP11SlotListWrapperFactory
2022-05-16 11:34:03,635 DEBUG [org.cesecore.keys.token.p11.Pkcs11SlotLabel] (default task-1) >getSunP11ProviderInputStream: -1, /usr/lib/x86_64-linux-gnu/libmpcm-pkcs11.so, Slot Number, null, null
2022-05-16 11:34:03,635 DEBUG [org.cesecore.keys.token.p11.Pkcs11SlotLabel] (default task-1) name = libmpcm-pkcs11.so-slot-1
library = /usr/lib/x86_64-linux-gnu/libmpcm-pkcs11.so
slot = -1
attributes(*, CKO_PUBLIC_KEY, *) = {
  CKA_TOKEN = false
  CKA_ENCRYPT = true
  CKA_VERIFY = true
  CKA_WRAP = true
}
attributes(*, CKO_PRIVATE_KEY, *) = {
  CKA_DERIVE = false
  CKA_TOKEN = true
  CKA_PRIVATE = true
  CKA_SENSITIVE = true
  CKA_EXTRACTABLE = false
  CKA_DECRYPT = true
  CKA_SIGN = true
  CKA_UNWRAP = true
}
disabledMechanisms = {
  CKM_SHA1_RSA_PKCS
  CKM_SHA256_RSA_PKCS
  CKM_SHA384_RSA_PKCS
  CKM_SHA512_RSA_PKCS
  CKM_MD2_RSA_PKCS
  CKM_MD5_RSA_PKCS
  CKM_DSA_SHA1
  CKM_ECDSA_SHA1
}
attributes(*, CKO_SECRET_KEY, *) = {
  CKA_SENSITIVE = true
  CKA_EXTRACTABLE = false
  CKA_ENCRYPT = true
  CKA_DECRYPT = true
  CKA_SIGN = true
  CKA_VERIFY = true
  CKA_WRAP = true
  CKA_UNWRAP = true
}

2022-05-16 11:34:03,635 DEBUG [org.cesecore.keys.token.p11.Pkcs11SlotLabel] (default task-1) Using JDK9 (and later) SUN PKCS11 provider: SunPKCS11
2022-05-16 11:34:03,655 DEBUG [org.cesecore.keys.token.p11.Pkcs11SlotLabel] (default task-1) Created JDK9 (and later) SUN PKCS11 provider: SunPKCS11-libmpcm-pkcs11.so-slot-1
2022-05-16 11:34:03,656 DEBUG [org.cesecore.keys.token.p11.Pkcs11SlotLabel] (default task-1) Found 7 slots for '/usr/lib/x86_64-linux-gnu/libmpcm-pkcs11.so'
`

**Comment by primetomas** [comment]
I could reproduce the issue using the container. So it is something with P11 on the container. We will look into it.

**Comment by primetomas** [comment]
the OpenJDK method signature in itself does not seem to have changed at all.
Method signature of PKCS11 seems to not have changed. https://github.com/openjdk/jdk/blob/master/src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/wrapper/PKCS11.java

**Comment by primetomas** [comment]
Solved in this issue, thank for the report.
https://jira.primekey.se/browse/ECA-10758
Unclear at the moment when we can push out a new container with this fix.
