### ISSUE TITLE
[BUG] NoClassDefFoundError exception for EJBCA WS CLI 

### ISSUE THREAD

**Issue by kuffel** [Keyfactor/ejbca-ce#616]
Using `ant clientToolBox` creates an executable that always fails with an `NoClassDefFoundError` exception.

**To Reproduce**

```bash
git clone git@github.com:Keyfactor/ejbca-ce.git
cd ejbca-ce
ant clientToolBox
./dist/ejbca-ws-cli/ejbcawsracli.sh finduser
```

**Expected Behavior**

Assuming everything is configured correctly i expect this:

```bash
./ejbcawsracli.sh finduser USERNAME EQUALS someone
No matching users could be found in database
```

**Current Behavior**

```bash
./ejbcawsracli.sh finduser USERNAME EQUALS someone

Exception in thread "main" java.lang.NoClassDefFoundError: org/ejbca/core/protocol/ws/client/gen/AuthorizationDeniedException_Exception
        at org.ejbca.core.protocol.ws.client.EJBCAWSRACommandFactory.getCommand(EJBCAWSRACommandFactory.java:45)
        at org.ejbca.core.protocol.ws.client.ejbcawsracli.main(ejbcawsracli.java:35)
Caused by: java.lang.ClassNotFoundException: org.ejbca.core.protocol.ws.client.gen.AuthorizationDeniedException_Exception
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 2 more
```

 - OS: Linux 5.15.0-87-generic 97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - OpenJDK Runtime Environment Temurin-22.0.1+8 (build 22.0.1+8)
 - OpenJDK 64-Bit Server VM Temurin-22.0.1+8 (build 22.0.1+8, mixed mode, sharing)
 - Apache Ant(TM) version 1.10.12 compiled on January 17 1970

**Comment by primetomas** [comment]
Oh, I didn't know the ./ejbcawsracli.sh script was still around. It should not be, I'll make sure to remove that for the next release as it's not updated.
You should use clientToolBox instead, that works.
cd dist/clientToolBox
./ejbcaClientToolBox.sh EjbcaWsRaCli finduser USERNAME EQUALS someone

**Comment by primetomas** [comment]
Removing the old scripts in the next major release. Thanks for the report.

**Comment by kuffel** [comment]
That works perfectly. Thanks for the quick help!
